name: CI

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install
          pnpm install -C packages/core
          pnpm install -C packages/adapter

      - name: Test adapters
        run: pnpm exec nx test adapter
        env:
          TONX_API_KEY: ${{ secrets.TONX_API_KEY }}

      - name: Build
        run: |
          pnpm exec nx build core
          pnpm exec nx build adapter

      - name: Collect built packages
        run: |
          mkdir upload
          mv packages/core/dist upload/tonx-core
          mv packages/adapter/dist upload/tonx-adapter

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: upload
